unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Related_Projects__c</fullName>
        <description>This field counts sum of related projects.</description>
        <label>Related Projects</label>
        <summaryForeignKey>Project__c.Opportunity__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/OpportunityTriggerHelper.cls
public class OpportunityTriggerHelper {
    
    // this method returns only those opportunities
    // whose Probabilty is greater than 80%
    public static List<Opportunity> filterOpportunities(Map<Id, Opportunity> oldMap, List<Opportunity> newList) {
        
        List<Opportunity> opportunities = new List<Opportunity>();
        
        if( ( oldMap == null && newList != null ) || ( oldMap != null && newList != null )) {
            
            for(Opportunity opportunityNew :newList) {
                if( oldMap == null && opportunityNew.Probability > 80 || ( oldMap != null && (opportunityNew.Probability > 80
                                                           &&(oldMap.get( opportunityNew.Id ).Probability != opportunityNew.Probability)))) {
                    opportunities.add(opportunityNew);
                }
            }
            
        }
        return opportunities;
    }
        
    public static void createProject(List<Opportunity> opportunities) {
        List<Project__c> projectsToInsert = new List<Project__c>();
        
        for(Opportunity opptyItem :createRelatedProject(opportunities)) {
            projectsToInsert.add(new Project__c(Name = opptyItem.Name, Description__c = opptyItem.Description, 
                                                Opportunity__c = opptyItem.Id, Primary_Contact__c = opptyItem.Account.Primary_Contact__c));
        }
        
        try{
            insert projectsToInsert; 
        } catch(DMLException e) {
            System.debug(e.getMessage());
        }
        
    }
    
    //this method ommit opportunities which already have related Project
    private static List<Opportunity> createRelatedProject(List<Opportunity> opportunities) {
        if(opportunities.isEmpty()) return new List<Opportunity>();
        
        List<Opportunity> filteredOpportunities = new List<Opportunity>();
        
        for(Opportunity opptyItem :opportunities) {
            if(opptyItem.Related_Projects__c == 0) { filteredOpportunities.add(opptyItem); }
        }
        return filteredOpportunities;
        
    }
    
}