unpackaged/objects/Billing_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Billing Rules</relationshipLabel>
        <relationshipName>Billing_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Billing Rule</label>
    <nameField>
        <label>Billing Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Rule</label>
        <referenceTo>Billing_Rule__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Time__c.object
<CustomObject>
    <fields>
        <fullName>Billing_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Rule</label>
        <referenceTo>Billing_Rule__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task</label>
        <referenceTo>Task__c</referenceTo>
        <relationshipLabel>Times</relationshipLabel>
        <relationshipName>Times</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Time</label>
    <nameField>
        <label>Time Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Times</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/TimeReportingController.cls
public with sharing class TimeReportingController {
	
    Contact contact {get; set;}
    List<CContact> cContacts {get; set;}
    
    public TimeReportingController() {
        contact = new Contact();
    }
    
    
    public List<CContact> getContacts() {
        if(cContacts == null) {
            cContacts = new List<CContact>();
            
            for(Contact c: [SELECT Name FROM Contact LIMIT 5]) {
                cContacts.add(new CContact(c, new Project__c(), new Task__c(), new Billing_Rule__c(), new Time__c()));
            }
        }
        return cContacts;
    }    
    
    public class CContact {
        
        public Contact cont {get; set;}
        public Project__c project {get; set;}
        public Task__c task {get; set;}
        public Billing_Rule__c billingRule {get; set;}
        public Time__c calendarTime {get; set;}
        
        public CContact(Contact c, Project__c p, Task__c task, Billing_Rule__c b, Time__c t) {
            this.cont = c;
            this.project = p;
            this.task = task;
            this.billingRule = b;
            this.calendarTime = t;
        }
        
    }
    
}